language: cpp

matrix:
    include:
        - os: osx
          osx_image: xcode11.1

before_install:
    - $TRAVIS_BUILD_DIR/.travis/before-install-$TRAVIS_OS_NAME.sh

before_script:
    - mkdir build && cd build
    - $TRAVIS_BUILD_DIR/.travis/before-script-$TRAVIS_OS_NAME.sh

script:
    - travis_wait 60 $TRAVIS_BUILD_DIR/.travis/script-$TRAVIS_OS_NAME.sh

before_deploy:
    - mkdir -p $HOME/binaries/ffmpeg-ext
    - tar czf $HOME/binaries/ffmpeg-ext/ffmpeg-ext-$TRAVIS_OS_NAME-$TRAVIS_COMMIT.tgz $TRAVIS_BUILD_DIR/build/install-ext/*
    - export S3_URL=http://scintillator-synth-coverage.s3-website-us-west-1.amazonaws.com/binaries/ffmpeg-ext/ffmpeg-ext-$TRAVIS_OS_NAME-$TRAVIS_COMMIT.tgz
    - echo '<html><head><meta http-equiv="refresh" content="0; url="$S3_URL" /></head></html>' > $HOME/binaries/ffmpeg-ext-latest-$TRAVIS_OS_NAME.html

deploy:
    - provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: scintillator-synth-coverage
      local-dir: $HOME/binaries
      upload-dir: .
      verbose: true
      edge: true
      cleanup: false
      acl: public_read
      on:
        branch: master
